include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    unnecessary_string_interpolations: false

analyzer:
  strong-mode:
    implicit-casts: true
  errors:
    todo: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
