import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../core/text/arabic_search.dart';

/// One Algerian commune — the Arabic name the user picks, plus the Latin
/// spelling so a name typed on a Latin keyboard still finds it.
class Commune {
  const Commune(this.name, this.latin);

  /// Display name, always Arabic — the app is Arabic-first.
  final String name;

  /// French/Latin spelling, kept for search and for future bilingual use.
  final String latin;

  @override
  String toString() => '$name ($latin)';
}

/// Every wilaya and all 1,541 Algerian communes, bundled with the app.
///
/// Why a bundled asset and not an API call: the picker has to open instantly
/// and work with no signal. Most users are on metered mobile data and a spinner
/// in the middle of a form is where they give up. The file is 54 KB and is
/// parsed once per process.
///
/// The dataset is generated by `tool/gen_communes.py` — read that script before
/// changing this one. It is the official national count of 1,541 communes, it
/// is checked wilaya by wilaya against the app's own taxonomy, and the upstream
/// name lists are MIT-licensed.
class CommuneIndex {
  CommuneIndex._();

  /// The dataset is immutable, so one parsed copy is shared process-wide.
  static final CommuneIndex instance = CommuneIndex._();

  static const String assetPath = 'assets/data/communes_dz.json';

  Map<String, List<Commune>> _byWilaya = const {};
  Map<String, String> _wilayaNames = const {};
  Future<void>? _loading;

  bool get isLoaded => _byWilaya.isNotEmpty;

  /// Total number of communes held, 0 before [load] completes.
  int get total =>
      _byWilaya.values.fold(0, (sum, list) => sum + list.length);

  /// Parse the asset once; concurrent callers share a single load.
  Future<void> load() => _loading ??= _parse();

  Future<void> _parse() async {
    final raw = await rootBundle.loadString(assetPath);
    final data = jsonDecode(raw) as Map<String, dynamic>;
    final wilayas = data['wilayas'] as Map<String, dynamic>;
    final communes = data['communes'] as Map<String, dynamic>;

    _byWilaya = {
      for (final entry in communes.entries)
        entry.key: [
          for (final row in (entry.value as List))
            Commune((row as List)[0] as String, row[1] as String),
        ],
    };
    _wilayaNames = {
      for (final entry in wilayas.entries)
        entry.key: (entry.value as Map)['ar'] as String,
    };
  }

  /// Wilaya ids are zero-padded in the taxonomy (`'01'`) but plain in the
  /// dataset (`'1'`); without this the picker would silently come up empty.
  static String _key(String wilayaId) {
    final n = int.tryParse(wilayaId.trim());
    return n == null ? wilayaId.trim() : '$n';
  }

  /// All communes of one wilaya, in alphabetical Arabic order.
  ///
  /// Loads the dataset on first use. An unknown wilaya id yields an empty list
  /// rather than throwing — the form still works, it just has nothing to offer.
  Future<List<Commune>> forWilaya(String wilayaId) async {
    await load();
    return inWilaya(wilayaId);
  }

  /// Synchronous read, for callers that already awaited [load].
  List<Commune> inWilaya(String wilayaId) =>
      _byWilaya[_key(wilayaId)] ?? const <Commune>[];

  /// Arabic display name of a wilaya as stored in the dataset.
  String? wilayaName(String wilayaId) => _wilayaNames[_key(wilayaId)];

  int countFor(String wilayaId) => inWilaya(wilayaId).length;

  /// Communes of one wilaya matching what the user typed.
  ///
  /// Matching is folded ([ArabicSearch]), so `احمد` finds `أحمد`, `تلمسان`
  /// finds `تلمسان`, and a Latin keyboard still works: `hussein dey` finds
  /// `حسين داي` because the Latin spelling is searched too. An empty query
  /// returns the whole wilaya; [limit] caps the rendered slice without hiding
  /// the true match count.
  List<Commune> search(String wilayaId, String query, {int limit = 80}) {
    final all = inWilaya(wilayaId);
    if (query.trim().isEmpty) return all;
    return [
      for (final c in all)
        if (ArabicSearch.matches(query, [c.name, c.latin])) c,
    ].take(limit).toList();
  }

  /// Number of communes of [wilayaId] matching [query] — used for the
  /// "N بلدية" line, which must not lie when [search] truncates the list.
  int searchCount(String wilayaId, String query) {
    if (query.trim().isEmpty) return countFor(wilayaId);
    final all = inWilaya(wilayaId);
    var n = 0;
    for (final c in all) {
      if (ArabicSearch.matches(query, [c.name, c.latin])) n++;
    }
    return n;
  }

  /// Drop the parsed dataset. Only for tests, which need a cold start.
  void resetForTest() {
    _byWilaya = const {};
    _wilayaNames = const {};
    _loading = null;
  }
}
