import 'dart:convert';

import 'package:flutter/services.dart' show CachingAssetBundle, rootBundle;

import '../core/text/arabic_search.dart';

/// One Algerian commune — the Arabic name the user picks, plus the Latin
/// spelling so a name typed on a Latin keyboard still finds it.
class Commune {
  const Commune(this.name, this.latin);

  /// Display name, always Arabic — the app is Arabic-first.
  final String name;

  /// French/Latin spelling, kept for search and for future bilingual use.
  final String latin;

  @override
  String toString() => '$name ($latin)';
}

/// Every wilaya and all 1,541 Algerian communes, bundled with the app.
///
/// Why a bundled asset and not an API call: the picker has to open instantly
/// and work with no signal. Most users are on metered mobile data and a spinner
/// in the middle of a form is where they give up. The file is 54 KB and is
/// parsed once per process.
///
/// The dataset is generated by `tool/gen_communes.py` — read that script before
/// changing this one. It is the official national count of 1,541 communes, it
/// is checked wilaya by wilaya against the app's own taxonomy, and the upstream
/// name lists are MIT-licensed.
class CommuneIndex {
  CommuneIndex._();

  /// The dataset is immutable, so one parsed copy is shared process-wide.
  static final CommuneIndex instance = CommuneIndex._();

  static const String assetPath = 'assets/data/communes_dz.json';

  Map<String, List<Commune>> _byWilaya = const {};
  Map<String, String> _wilayaNames = const {};
  Future<void>? _loading;

  bool get isLoaded => _byWilaya.isNotEmpty;

  /// Total number of communes held, 0 before [load] completes.
  int get total =>
      _byWilaya.values.fold(0, (sum, list) => sum + list.length);

  /// Parse the asset once; concurrent callers share a single load.
  ///
  /// **The cache is the attempt, not the dataset — so a failed attempt must be
  /// forgotten.** `load()` used to be `_loading ??= _parse()` and nothing ever
  /// cleared the field on a throw, which made the cached future the *memory of
  /// the try*: an unreadable asset (a corrupt build, a half-written file, a
  /// decode failure) left the already-rejected future sitting in `_loading`, and
  /// every later `await load()` re-awaited that same rejection instead of
  /// reading the asset again. The app therefore never made a second attempt for
  /// the rest of the process, and the one caller that can repair it —
  /// [resetForTest] — is called by tests only. In production the failure was
  /// permanent: the commune picker came up empty for the whole session and the
  /// publish form asked for the commune of a wilaya the app holds all 1,541
  /// communes for.
  ///
  /// Clearing on failure keeps the two guarantees apart. Concurrent callers
  /// still share exactly one parse, because a load that is *in flight* stays
  /// cached; only an attempt that has already **failed** is dropped, so the
  /// next caller gets a real second try. The caller still sees the original
  /// error — it is rethrown, never swallowed — so the sheet that asked for the
  /// list still knows the dataset is unavailable.
  Future<void> load() {
    final pending = _loading;
    if (pending != null) return pending;
    // The write-back is guarded so that two *different* in-flight loads cannot
    // leave the field holding a future this call did not start.
    final attempt = _parse();
    _loading = attempt;
    return attempt.whenComplete(() {
      if (!identical(_loading, attempt)) return;
      _loading = null;
      // **The failed read is cached by the framework too, and that half is
      // outside this class.** `rootBundle` is a `PlatformAssetBundle`, whose
      // `loadString` memoises with `putIfAbsent` — and `putIfAbsent` stores the
      // future *before* it is awaited, so a rejected read is remembered exactly
      // like a good one. (The framework says so itself on
      // `loadStructuredData`: «Failures are not cached» — `loadString` is the
      // one that keeps them.) Clearing only `_loading` therefore fixed nothing
      // the user can see: the retry re-read straight out of that cache and
      // failed with the identical error, forever. The retry is only real once
      // the memo that holds the rejection is dropped as well.
      _clearAssetCache();
    });
  }

  /// Drops the framework's memo for the dataset asset, so the next [load]
  /// performs a real read instead of replaying a remembered failure.
  ///
  /// [rootBundle] is typed as [AssetBundle] because the SDK exposes it that
  /// way, and the clearing method is only on the caching subclass. Anything
  /// that is not a [CachingAssetBundle] has no memo to drop, so the call is
  /// simply absent — which also keeps a test that injects a plain bundle
  /// working.
  static void _clearAssetCache() {
    final bundle = rootBundle;
    if (bundle is CachingAssetBundle) bundle.clear();
  }

  Future<void> _parse() async {
    final raw = await rootBundle.loadString(assetPath);
    final data = jsonDecode(raw) as Map<String, dynamic>;
    final wilayas = data['wilayas'] as Map<String, dynamic>;
    final communes = data['communes'] as Map<String, dynamic>;

    _byWilaya = {
      for (final entry in communes.entries)
        entry.key: [
          for (final row in (entry.value as List))
            Commune((row as List)[0] as String, row[1] as String),
        ],
    };
    _wilayaNames = {
      for (final entry in wilayas.entries)
        entry.key: (entry.value as Map)['ar'] as String,
    };
  }

  /// Wilaya ids are zero-padded in the taxonomy (`'01'`) but plain in the
  /// dataset (`'1'`); without this the picker would silently come up empty.
  static String _key(String wilayaId) {
    final n = int.tryParse(wilayaId.trim());
    return n == null ? wilayaId.trim() : '$n';
  }

  /// All communes of one wilaya, in alphabetical Arabic order.
  ///
  /// Loads the dataset on first use. An unknown wilaya id yields an empty list
  /// rather than throwing — the form still works, it just has nothing to offer.
  Future<List<Commune>> forWilaya(String wilayaId) async {
    await load();
    return inWilaya(wilayaId);
  }

  /// Synchronous read, for callers that already awaited [load].
  List<Commune> inWilaya(String wilayaId) =>
      _byWilaya[_key(wilayaId)] ?? const <Commune>[];

  /// Arabic display name of a wilaya as stored in the dataset.
  String? wilayaName(String wilayaId) => _wilayaNames[_key(wilayaId)];

  int countFor(String wilayaId) => inWilaya(wilayaId).length;

  /// Communes of one wilaya matching what the user typed.
  ///
  /// Matching is folded ([ArabicSearch]), so `احمد` finds `أحمد`, `تلمسان`
  /// finds `تلمسان`, and a Latin keyboard still works: `hussein dey` finds
  /// `حسين داي` because the Latin spelling is searched too. An empty query
  /// returns the whole wilaya; [limit] caps the rendered slice without hiding
  /// the true match count.
  List<Commune> search(String wilayaId, String query, {int limit = 80}) {
    final all = inWilaya(wilayaId);
    if (query.trim().isEmpty) return all;
    return [
      for (final c in all)
        if (ArabicSearch.matches(query, [c.name, c.latin])) c,
    ].take(limit).toList();
  }

  /// Number of communes of [wilayaId] matching [query] — used for the
  /// "N بلدية" line, which must not lie when [search] truncates the list.
  int searchCount(String wilayaId, String query) {
    if (query.trim().isEmpty) return countFor(wilayaId);
    final all = inWilaya(wilayaId);
    var n = 0;
    for (final c in all) {
      if (ArabicSearch.matches(query, [c.name, c.latin])) n++;
    }
    return n;
  }

  /// Drop the parsed dataset. Only for tests, which need a cold start.
  void resetForTest() {
    _byWilaya = const {};
    _wilayaNames = const {};
    _loading = null;
  }
}
